# Generated by Django 4.0.2 on 2022-02-20 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='def_answer',
        ),
    ]
