# Generated by Django 4.0.2 on 2022-02-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0002_remove_question_def_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='default_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
