# Generated by Django 4.0.2 on 2022-02-19 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Survey', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
